# Generated by Django 5.2.3 on 2025-07-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotiontracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotionlog',
            name='meeting_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
