# Generated by Django 5.2.3 on 2025-07-03 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
