# Generated by Django 5.2.3 on 2025-07-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_quiz_quizattempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='student',
        ),
        migrations.RenameField(
            model_name='teacherprofile',
            old_name='emergency_name',
            new_name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='emergency_phone',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='emergency_relation',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='subject',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='emergency_contact_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='QuizAttempt',
        ),
    ]
