# Generated by Django 5.2.3 on 2025-07-08 15:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_classroom_announcement_classroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmeeting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scheduledmeeting',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.classroom'),
        ),
        migrations.AlterField(
            model_name='scheduledmeeting',
            name='topic',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='scheduledmeeting',
            name='zoom_meeting_id',
            field=models.CharField(max_length=100),
        ),
    ]
