# Generated by Django 5.2.3 on 2025-07-09 10:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_remove_studentprofile_classroom_studentclassroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledmeeting',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='scheduledmeeting',
            name='zoom_meeting_id',
        ),
        migrations.AlterField(
            model_name='scheduledmeeting',
            name='classroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.classroom'),
            preserve_default=False,
        ),
    ]
