# Generated by Django 5.2.3 on 2025-07-10 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_scheduledmeeting_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='behaviornote',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.classroom'),
        ),
    ]
