# Generated by Django 5.2.3 on 2025-07-10 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_manualstudent_classroom_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualstudent',
            name='classroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.classroom'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manualstudent',
            name='classroom_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='manualstudent',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='manualstudent',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='manualstudent',
            name='roll_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
