# Generated by Django 5.2.3 on 2025-07-11 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_attentionlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttentionLog',
        ),
    ]
