# Generated by Django 5.2.3 on 2025-06-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_selector', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chathistory',
            name='persona',
        ),
        migrations.AddField(
            model_name='chathistory',
            name='mentor_type',
            field=models.CharField(default='strict', max_length=20),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='session_id',
            field=models.CharField(default='default-session', max_length=100),
        ),
    ]
