# Generated by Django 5.2 on 2025-07-11 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classrecording',
            name='allowed_students',
        ),
        migrations.DeleteModel(
            name='RecordingAccess',
        ),
    ]
