# Generated by Django 5.2 on 2025-07-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0002_studysession_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='voice_note',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='voice',
            field=models.FileField(blank=True, null=True, upload_to='chat_voices/'),
        ),
    ]
