# Generated by Django 5.2 on 2025-07-11 17:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0003_remove_chatmessage_voice_note_chatmessage_voice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionprogress',
            old_name='time_spent',
            new_name='time_spent_minutes',
        ),
        migrations.RenameField(
            model_name='sessionprogress',
            old_name='topics_covered',
            new_name='topics',
        ),
        migrations.AddField(
            model_name='sessionprogress',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sessionprogress',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
