# Generated by Django 5.2.3 on 2025-07-11 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
