# Generated by Django 5.2.3 on 2025-07-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling_mode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='age',
            field=models.IntegerField(),
        ),
    ]
